name: symfony-5.4
recipe: symfony
config:
  webroot: .
  php: '8.1'
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  database:
    creds:
      user: symfony5.4
      password: symfony5.4
      database: symfony5.4