#index:
#    path: /
#    controller: App\Controller\DefaultController::index
legacy_doc:
  path: /legacy/doc
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    # this value can be an absolute path or an absolute URL
    path: 'https://legacy.example.com/doc'
    permanent: true
blog_index:
  path:       /
  controller: App\Controller\BlogController::index